### PR TITLE
Fixed GeoJSON polygon format

### LINKED ISSUE #97: Polygon GeoJSON format
At the moment GeoJSON format in spec is incorrect. This needs to be changed and fixed in API

### PR DESCRIPTION
**Pull request by jarinykanen**
Resolves #97 

Changed geoShape persistence model to user geometry data type
Added needed DB migrations
Added common geometry package
Fixed tests

### CODE REVIEW

File: src/main/kotlin/fi/metatavu/muisti/geometry/GeometryTransformer.kt [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+      coordinates.add(Coordinate(coordinate[0], coordinate[1]))
+    }
+  }
+
+  return geometryFactory.createPolygon(coordinates.toTypedArray())
+}
+
+/**
+ * Convert Geometry Polygon from entity to spec Polygon.
+ * Note: Since each room can only have one shape we can hardcode the first index to 0.
```
Comment (anttileppa) [inline src/main/kotlin/fi/metatavu/muisti/geometry/GeometryTransformer.kt:33]: does this note actually belong to this method? seems a bit specific for generic function
